<?php

namespace App\Swagger;

/**
 * @OA\Parameter(
 *     parameter="MealPlanIndexYearParam",
 *     name="year",
 *     in="query",
 *     description="取得対象の年（1900〜2100）",
 *     required=true,
 *     @OA\Schema(
 *         type="integer",
 *         minimum=1900,
 *         maximum=2100,
 *         example=2024
 *     )
 * )
 * @OA\Parameter(
 *     parameter="MealPlanIndexMonthParam",
 *     name="month",
 *     in="query",
 *     description="取得対象の月（1〜12）",
 *     required=true,
 *     @OA\Schema(
 *         type="integer",
 *         minimum=1,
 *         maximum=12,
 *         example=1
 *     )
 * )
 * @OA\Parameter(
 *     parameter="MealPlanDateParam",
 *     name="date",
 *     in="path",
 *     description="献立の日付（Y-m-d）",
 *     required=true,
 *     @OA\Schema(
 *         type="string",
 *         format="date",
 *         example="2024-01-15"
 *     )
 * )
 * @OA\Parameter(
 *     parameter="MealPlanIdParam",
 *     name="id",
 *     in="path",
 *     description="献立ID",
 *     required=true,
 *     @OA\Schema(
 *         type="string",
 *         example="1"
 *     )
 * )
 * @OA\Parameter(
 *     parameter="MealPlanIdPathParam",
 *     name="mealPlanId",
 *     in="path",
 *     description="献立ID",
 *     required=true,
 *     @OA\Schema(
 *         type="string",
 *         format="uuid"
 *     )
 * )
 * @OA\Parameter(
 *     parameter="MealIdParam",
 *     name="mealId",
 *     in="path",
 *     description="献立の1食ID",
 *     required=true,
 *     @OA\Schema(
 *         type="string",
 *         format="uuid"
 *     )
 * )
 * @OA\Parameter(
 *     parameter="MealCategoryIdParam",
 *     name="id",
 *     in="path",
 *     description="献立カテゴリID",
 *     required=true,
 *     @OA\Schema(
 *         type="string",
 *         example="1"
 *     )
 * )
 */

class MealPlanParameters {}
