@startuml
hide circle

entity ingredients {
    * id : string <<generated>>
    --
    * name : string
    * group_id : string <<FK>>
}

entity ingredient_units {
    * id : string <<generated>>
    --
    * name : string
    * group_id : string <<FK>>
}

entity seasonings {
    * id : string <<generated>>
    --
    * name : string
    * group_id : string <<FK>>
}

entity seasoning_units {
    * id : string <<generated>>
    --
    * name : string
    * group_id : string <<FK>>
}

entity dish_category_mappings {
    * dish_id : string <<FK>>
    * category_id : string <<FK>>
}

entity dishes {
    * id : string <<generated>>
    --
    * name : string
    * thumbnail_url : string / サムネイル画像URL
    * url : string / レシピURL
    * recipe : string / レシピ（テキスト入力）
    * memo : string / メモ
    * group_id : string <<FK>>
}

entity dish_ingredient_mappings {
    * dish_id : string <<FK>>
    * ingredient_id : string <<FK>>
    --
    * amount : float
    * unit_id : string <<FK>>
}

entity dish_seasoning_mappings {
    * dish_id : string <<FK>>
    * ingredient_id : string <<FK>>
    --
    * amount : float
    * unit_id : string <<FK>>
}

entity dish_roles {
    * id : string <<generated>>
    ---
    * name : string / 種別（主食、主菜、副菜、汁物、その他）
    * group_id : string <<FK>>
}

entity dish_categories {
    * id : string <<generated>>
    --
    * name : string
    * group_id : string <<FK>>
}

entity groups {
    * id : string <<generated>>
    * group_size : number / グループに属するユーザの数
}

entity meal_dish_mappings {
    * meal_id : string <<FK>>
    * dish_id : string <<FK>>
    * dish_role_id : string <<FK>>
}

entity meals {
    * id : string <<generated>>
    ---
    * date : date
    * group_id : string <<FK>>
    * meal_category_id : string <<FK>>
}


entity meal_categories {
    * id : string <<generated>>
    --
    * name : string
    * color_id : string <<FK>>
    * group_id : string <<FK>>
}

entity meal_category_colors {
    * id : string <<generated>>
    --
    * name : string / 色名（イエロー, オレンジ, ピンク, レッド, 
        イエローグリーン, グリーン, スカイブルー, ブルー, パープル）
    * color_code: string / 色コード
    * group_id : string <<FK>>
}

entity shopping_items {
    * id : string <<generated>>
    --
    * name : string
    * is_pinned : boolean / trueの場合、リスト上部に固定化する
    * is_checked : boolean / trueの場合、アイテムにチェックマークが付く
    * order : int / ソート順
    * group_id : string <<FK>>
    * category_id : string <<FK>>
}

entity shopping_categories {
    * id : string <<generated>>
    --
    * name : string
    * is_default : boolean / trueの場合、デフォルトカテゴリとして扱う
    * order : int / ソート順
    * group_id : string <<FK>>
}

entity shopping_tags {
    * id : string <<generated>>
    --
    * name : string
    * group_id : string <<FK>>
}

entity shopping_item_tag_mappings {
    * shopping_item_id : string <<FK>>
    * shopping_tag_id : string <<FK>>
}

entity group_user_mappings {
    * user_id : string <<FK>>
    * group_id : string <<FK>>
}

entity users {
    * id : string <<generated>>
    --
    * name : string
    * email : string
    password : string / ログイン用パスワード（ソーシャルログインでは使用しない）
    avatar_url : string / プロフィール画像URL
    provider : string / プロバイダ名（例: 'google'）
    provider_id : string / ソーシャルログイン用ID
    * created_at : date
    * updated_at : date
}

entity invitation_tokens {
    * id : string <<generated>>
    --
    * inviter_id : string <<FK>>
    * token : string
    * expires_at : date
}

groups ||--|| group_user_mappings
group_user_mappings ||--|| users
users ||--o{ invitation_tokens

groups ||--o{ shopping_items
groups ||--o{ shopping_categories
groups ||--o{ shopping_tags
shopping_categories ||--o{ shopping_items
shopping_items ||--o{ shopping_item_tag_mappings
shopping_tags }o--|| shopping_item_tag_mappings

groups ||--o{ meal_categories
groups ||--o{ meal_category_colors
meal_categories |o--|| meal_category_colors

meals }o--|| groups
meals }o--|| meal_categories
dish_roles }o--|| groups
dishes }o--|| groups
dishes ||--o{ meal_dish_mappings
meals ||--o{ meal_dish_mappings
meal_dish_mappings }o--|| dish_roles

groups ||--o{ dish_categories
dishes ||--o{ dish_category_mappings
dish_category_mappings }o--|| dish_categories

ingredient_units }o--|| groups
ingredients }o--|| groups
dishes ||--o{ dish_ingredient_mappings
dish_ingredient_mappings }o--|| ingredient_units
dish_ingredient_mappings }o--|| ingredients


seasoning_units }o--|| groups
seasonings }o--|| groups
dishes ||--o{ dish_seasoning_mappings
dish_seasoning_mappings }o--|| seasoning_units
dish_seasoning_mappings }o--|| seasonings


note left of groups
  データ共有するユーザー情報を管理する。
  ユーザは１つのグループにのみ所属できる。（拡張可能性あり）
  もしくは、すでに存在しているグループに招待してもらって所属する。
end note

note left of meals
  献立情報を管理する。
end note

note left of meal_categories
  献立種別を管理する。（朝食、昼食、夕食など）
end note

note right of dishes
  料理情報を管理する。
end note

note top of dish_roles
  料理区分を管理する。（料理カテゴリとは別物）
end note

note right of dish_categories
  料理カテゴリを管理する。
end note

note right of invitation_tokens
  ユーザ招待トークンを管理する。
  グループに招待するときにトークンを発行する。
  一定時間でトークンは使用できなくなり、テーブルからデータを消去する。
end note


@enduml
