[supervisord]
nodaemon=true
user=www-data
logfile=/tmp/supervisord.log
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:php-fpm]
command=/usr/local/sbin/php-fpm -F
user=www-data
autostart=true
autorestart=true
stdout_logfile=/tmp/php-fpm.stdout.log
stdout_logfile_maxbytes=0
stderr_logfile=/tmp/php-fpm.stderr.log
stderr_logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
user=www-data
autostart=true
autorestart=true
stdout_logfile=/tmp/nginx.stdout.log
stdout_logfile_maxbytes=0
stderr_logfile=/tmp/nginx.stderr.log
stderr_logfile_maxbytes=0
